name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      ruby-version: 2.6
    defaults:
      run:
        working-directory: ./docs

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.ruby-version }}

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          gems-${{ runner.os }}-${{ env.ruby-version }}-
          gems-${{ runner.os }}-

    - run: bundle config set deployment 'true'
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - run: bundle exec middleman build

    - name: list directory
      run: |
        ls -l
        pwd
        ls -l ./build
        cat ../.gitignore || cat .gitignore || echo ok

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        allow_empty_commit: true
        enable_jekyll: true
        publish_dir: ./docs/build
        keep_files: true

    # - name: Commit and push changes
    #   run: |
    #     git config --global user.email "hayko5999@gamil.com"
    #     git config --global user.name "hayk96" 
    #     git fetch origin gh-pages
    #     git checkout gh-pages
    #     git add build     
    #     git commit --allow-empty -m "Committed at $(date)" --amend
    #     git push origin gh-pages -f