name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      ruby-version: 2.6
    defaults:
      run:
        working-directory: ./docs

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.ruby-version }}

    - uses: actions/cache@v2
      with:
        path: docs/vendor/bundle
        key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          gems-${{ runner.os }}-${{ env.ruby-version }}-
          gems-${{ runner.os }}-

    - run: bundle config set deployment 'true'
    - name: bundle install
      run: |
        bundle config path docs/vendor/bundle
        bundle install --jobs 4 --retry 3

    - run: bundle exec middleman build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        keep_files: true
